CITIES = [
    {"city_ru": "Москва", "iata": "SVO", "country_ru": "Россия",
     "wikivoyage_en": "Moscow", "wikipedia_fallback_en": "Moscow"},
    {"city_ru": "Санкт-Петербург", "iata": "LED", "country_ru": "Россия",
     "wikivoyage_en": "Saint Petersburg", "wikipedia_fallback_en": "Saint Petersburg"},
    {"city_ru": "Сочи", "iata": "AER", "country_ru": "Россия",
     "wikivoyage_en": "Sochi", "wikipedia_fallback_en": "Sochi"},
    {"city_ru": "Екатеринбург", "iata": "SVX", "country_ru": "Россия",
     "wikivoyage_en": "Yekaterinburg", "wikipedia_fallback_en": "Yekaterinburg"},
    {"city_ru": "Казань", "iata": "KZN", "country_ru": "Россия",
     "wikivoyage_en": "Kazan", "wikipedia_fallback_en": "Kazan"},
    {"city_ru": "Новосибирск", "iata": "OVB", "country_ru": "Россия",
     "wikivoyage_en": "Novosibirsk", "wikipedia_fallback_en": "Novosibirsk"},
    {"city_ru": "Владивосток", "iata": "VVO", "country_ru": "Россия",
     "wikivoyage_en": "Vladivostok", "wikipedia_fallback_en": "Vladivostok"},
    {"city_ru": "Краснодар", "iata": "KRR", "country_ru": "Россия",
     "wikivoyage_en": "Krasnodar", "wikipedia_fallback_en": "Krasnodar"},
    {"city_ru": "Уфа", "iata": "UFA", "country_ru": "Россия",
     "wikivoyage_en": "Ufa", "wikipedia_fallback_en": "Ufa"},
    {"city_ru": "Ростов-на-Дону", "iata": "ROV", "country_ru": "Россия",
     "wikivoyage_en": "Rostov-on-Don", "wikipedia_fallback_en": "Rostov-on-Don"},
    {"city_ru": "Нижний Новгород", "iata": "GOJ", "country_ru": "Россия",
     "wikivoyage_en": "Nizhny Novgorod", "wikipedia_fallback_en": "Nizhny Novgorod"},
    {"city_ru": "Самара", "iata": "KUF", "country_ru": "Россия",
     "wikivoyage_en": "Samara", "wikipedia_fallback_en": "Samara"},
    {"city_ru": "Омск", "iata": "OMS", "country_ru": "Россия",
     "wikivoyage_en": "Omsk", "wikipedia_fallback_en": "Omsk"},
    {"city_ru": "Иркутск", "iata": "IKT", "country_ru": "Россия",
     "wikivoyage_en": "Irkutsk", "wikipedia_fallback_en": "Irkutsk"},
    {"city_ru": "Хабаровск", "iata": "KHV", "country_ru": "Россия",
     "wikivoyage_en": "Khabarovsk", "wikipedia_fallback_en": "Khabarovsk"},
    {"city_ru": "Красноярск", "iata": "KJA", "country_ru": "Россия",
     "wikivoyage_en": "Krasnoyarsk", "wikipedia_fallback_en": "Krasnoyarsk"},
    {"city_ru": "Пермь", "iata": "PEE", "country_ru": "Россия",
     "wikivoyage_en": "Perm", "wikipedia_fallback_en": "Perm, Russia"},
    {"city_ru": "Воронеж", "iata": "VOZ", "country_ru": "Россия",
     "wikivoyage_en": "Voronezh", "wikipedia_fallback_en": "Voronezh"},
    {"city_ru": "Калининград", "iata": "KGD", "country_ru": "Россия",
     "wikivoyage_en": "Kaliningrad", "wikipedia_fallback_en": "Kaliningrad"},
    {"city_ru": "Тюмень", "iata": "TJM", "country_ru": "Россия",
     "wikivoyage_en": "Tyumen", "wikipedia_fallback_en": "Tyumen"},
    {"city_ru": "Мурманск", "iata": "MMK", "country_ru": "Россия",
     "wikivoyage_en": "Murmansk", "wikipedia_fallback_en": "Murmansk"},

    # Иностранные города
    {"city_ru": "Дубай", "iata": "DXB", "country_ru": "ОАЭ",
     "wikivoyage_en": "Dubai", "wikipedia_fallback_en": "Dubai"},
    {"city_ru": "Стамбул", "iata": "IST", "country_ru": "Турция",
     "wikivoyage_en": "Istanbul", "wikipedia_fallback_en": "Istanbul"},
    {"city_ru": "Анталья", "iata": "AYT", "country_ru": "Турция",
     "wikivoyage_en": "Antalya", "wikipedia_fallback_en": "Antalya"},
    {"city_ru": "Пекин", "iata": "PEK", "country_ru": "Китай",
     "wikivoyage_en": "Beijing", "wikipedia_fallback_en": "Beijing"},
    {"city_ru": "Бангкок", "iata": "BKK", "country_ru": "Таиланд",
     "wikivoyage_en": "Bangkok", "wikipedia_fallback_en": "Bangkok"},
    {"city_ru": "Дели", "iata": "DEL", "country_ru": "Индия",
     "wikivoyage_en": "Delhi", "wikipedia_fallback_en": "Delhi"},
    {"city_ru": "Ереван", "iata": "EVN", "country_ru": "Армения",
     "wikivoyage_en": "Yerevan", "wikipedia_fallback_en": "Yerevan"},
    {"city_ru": "Тбилиси", "iata": "TBS", "country_ru": "Грузия",
     "wikivoyage_en": "Tbilisi", "wikipedia_fallback_en": "Tbilisi"},
    {"city_ru": "Алматы", "iata": "ALA", "country_ru": "Казахстан",
     "wikivoyage_en": "Almaty", "wikipedia_fallback_en": "Almaty"},
    {"city_ru": "Ташкент", "iata": "TAS", "country_ru": "Узбекистан",
     "wikivoyage_en": "Tashkent", "wikipedia_fallback_en": "Tashkent"},
    {"city_ru": "Баку", "iata": "GYD", "country_ru": "Азербайджан",
     "wikivoyage_en": "Baku", "wikipedia_fallback_en": "Baku"},
    {"city_ru": "Минск", "iata": "MSQ", "country_ru": "Беларусь",
     "wikivoyage_en": "Minsk", "wikipedia_fallback_en": "Minsk"},
    {"city_ru": "Бишкек", "iata": "FRU", "country_ru": "Кыргызстан",
     "wikivoyage_en": "Bishkek", "wikipedia_fallback_en": "Bishkek"},
    {"city_ru": "Астана", "iata": "NQZ", "country_ru": "Казахстан",
     "wikivoyage_en": "Astana", "wikipedia_fallback_en": "Astana"},
    {"city_ru": "Самарканд", "iata": "SKD", "country_ru": "Узбекистан",
     "wikivoyage_en": "Samarkand", "wikipedia_fallback_en": "Samarkand"},
    {"city_ru": "Коломбо", "iata": "CMB", "country_ru": "Шри-Ланка",
     "wikivoyage_en": "Colombo", "wikipedia_fallback_en": "Colombo"},
    {"city_ru": "Мале", "iata": "MLE", "country_ru": "Мальдивы",
     "wikivoyage_en": "Malé", "wikipedia_fallback_en": "Malé"},
    {"city_ru": "Катманду", "iata": "KTM", "country_ru": "Непал",
     "wikivoyage_en": "Kathmandu", "wikipedia_fallback_en": "Kathmandu"},
    {"city_ru": "Денпасар", "iata": "DPS", "country_ru": "Индонезия",
     "wikivoyage_en": "Denpasar", "wikipedia_fallback_en": "Denpasar"},
    {"city_ru": "Гоа", "iata": "GOI", "country_ru": "Индия",
     "wikivoyage_en": "Goa", "wikipedia_fallback_en": "Goa"},
    {"city_ru": "Хургада", "iata": "HRG", "country_ru": "Египет",
     "wikivoyage_en": "Hurghada", "wikipedia_fallback_en": "Hurghada"},
    {"city_ru": "Шарм-эш-Шейх", "iata": "SSH", "country_ru": "Египет",
     "wikivoyage_en": "Sharm el-Sheikh", "wikipedia_fallback_en": "Sharm El Sheikh"},
    {"city_ru": "Пхукет", "iata": "HKT", "country_ru": "Таиланд",
     "wikivoyage_en": "Phuket", "wikipedia_fallback_en": "Phuket Province"},
    {"city_ru": "Куала-Лумпур", "iata": "KUL", "country_ru": "Малайзия",
     "wikivoyage_en": "Kuala Lumpur", "wikipedia_fallback_en": "Kuala Lumpur"},
    {"city_ru": "Абу-Даби", "iata": "AUH", "country_ru": "ОАЭ",
     "wikivoyage_en": "Abu Dhabi", "wikipedia_fallback_en": "Abu Dhabi"},
]