from backend.db.database import SessionLocal, init_db
from backend.db.models import Flight, MenuItem, CommercialOffer, Aircraft, Route

def seed():
    init_db()
    db = SessionLocal()

    db.query(CommercialOffer).delete()
    db.query(MenuItem).delete()
    db.query(Flight).delete()
    db.query(Aircraft).delete()
    db.query(Route).delete()

    # ФЛОТ (30 самолётов)
    fleet = [
        # Airbus A320 (12 штук)
        Aircraft(registration="RA-89001", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2015, status="active"),
        Aircraft(registration="RA-89002", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2016, status="active"),
        Aircraft(registration="RA-89003", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2017, status="active"),
        Aircraft(registration="RA-89004", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2017, status="active"),
        Aircraft(registration="RA-89005", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2018, status="active"),
        Aircraft(registration="RA-89006", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2018, status="maintenance"),
        Aircraft(registration="RA-89007", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2019, status="active"),
        Aircraft(registration="RA-89008", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2019, status="active"),
        Aircraft(registration="RA-89009", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2020, status="active"),
        Aircraft(registration="RA-89010", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2020, status="active"),
        Aircraft(registration="RA-89011", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2021, status="active"),
        Aircraft(registration="RA-89012", aircraft_type="Airbus A320",
                 manufacturer="Airbus", capacity_economy=150, capacity_business=12,
                 year_manufactured=2022, status="active"),
        # Airbus A321 (8 штук)
        Aircraft(registration="RA-73001", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2016, status="active"),
        Aircraft(registration="RA-73002", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2017, status="active"),
        Aircraft(registration="RA-73003", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2018, status="active"),
        Aircraft(registration="RA-73004", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2019, status="active"),
        Aircraft(registration="RA-73005", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2019, status="maintenance"),
        Aircraft(registration="RA-73006", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2020, status="active"),
        Aircraft(registration="RA-73007", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2021, status="active"),
        Aircraft(registration="RA-73008", aircraft_type="Airbus A321",
                 manufacturer="Airbus", capacity_economy=180, capacity_business=16,
                 year_manufactured=2022, status="active"),
        # Boeing 737 (10 штук)
        Aircraft(registration="RA-73101", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2014, status="active"),
        Aircraft(registration="RA-73102", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2015, status="active"),
        Aircraft(registration="RA-73103", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2016, status="active"),
        Aircraft(registration="RA-73104", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2017, status="active"),
        Aircraft(registration="RA-73105", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2017, status="maintenance"),
        Aircraft(registration="RA-73106", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2018, status="active"),
        Aircraft(registration="RA-73107", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2019, status="active"),
        Aircraft(registration="RA-73108", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2020, status="active"),
        Aircraft(registration="RA-73109", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2021, status="active"),
        Aircraft(registration="RA-73110", aircraft_type="Boeing 737-800",
                 manufacturer="Boeing", capacity_economy=162, capacity_business=12,
                 year_manufactured=2022, status="active"),
    ]
    db.add_all(fleet)

    # МАРШРУТЫ
    routes = [
        # Российские направления (20 городов)
        Route(destination_city="Санкт-Петербург", destination_iata="LED",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=85, distance_km=635),
        Route(destination_city="Сочи", destination_iata="AER",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=150, distance_km=1350),
        Route(destination_city="Екатеринбург", destination_iata="SVX",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=150, distance_km=1420),
        Route(destination_city="Казань", destination_iata="KZN",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=100, distance_km=820),
        Route(destination_city="Новосибирск", destination_iata="OVB",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=240, distance_km=2800),
        Route(destination_city="Владивосток", destination_iata="VVO",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=510, distance_km=6430),
        Route(destination_city="Краснодар", destination_iata="KRR",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=130, distance_km=1180),
        Route(destination_city="Уфа", destination_iata="UFA",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=130, distance_km=1160),
        Route(destination_city="Ростов-на-Дону", destination_iata="ROV",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=120, distance_km=1060),
        Route(destination_city="Нижний Новгород", destination_iata="GOJ",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=90, distance_km=780),
        Route(destination_city="Самара", destination_iata="KUF",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=110, distance_km=1040),
        Route(destination_city="Омск", destination_iata="OMS",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=210, distance_km=2230),
        Route(destination_city="Иркутск", destination_iata="IKT",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=330, distance_km=4190),
        Route(destination_city="Хабаровск", destination_iata="KHV",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=480, distance_km=6100),
        Route(destination_city="Красноярск", destination_iata="KJA",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=285, distance_km=3360),
        Route(destination_city="Пермь", destination_iata="PEE",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=140, distance_km=1385),
        Route(destination_city="Воронеж", destination_iata="VOZ",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=100, distance_km=520),
        Route(destination_city="Калининград", destination_iata="KGD",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=140, distance_km=1090),
        Route(destination_city="Тюмень", destination_iata="TJM",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=175, distance_km=1750),
        Route(destination_city="Мурманск", destination_iata="MMK",
              destination_country="Россия", is_domestic=1,
              flight_duration_min=155, distance_km=1880),
        # Международные направления (25 городов)
        Route(destination_city="Дубай", destination_iata="DXB",
              destination_country="ОАЭ", is_domestic=0,
              flight_duration_min=255, distance_km=3500),
        Route(destination_city="Стамбул", destination_iata="IST",
              destination_country="Турция", is_domestic=0,
              flight_duration_min=210, distance_km=1760),
        Route(destination_city="Анталья", destination_iata="AYT",
              destination_country="Турция", is_domestic=0,
              flight_duration_min=215, distance_km=1980),
        Route(destination_city="Пекин", destination_iata="PEK",
              destination_country="Китай", is_domestic=0,
              flight_duration_min=480, distance_km=5800),
        Route(destination_city="Бангкок", destination_iata="BKK",
              destination_country="Таиланд", is_domestic=0,
              flight_duration_min=570, distance_km=7600),
        Route(destination_city="Дели", destination_iata="DEL",
              destination_country="Индия", is_domestic=0,
              flight_duration_min=390, distance_km=4280),
        Route(destination_city="Ереван", destination_iata="EVN",
              destination_country="Армения", is_domestic=0,
              flight_duration_min=165, distance_km=1820),
        Route(destination_city="Тбилиси", destination_iata="TBS",
              destination_country="Грузия", is_domestic=0,
              flight_duration_min=165, distance_km=1790),
        Route(destination_city="Алматы", destination_iata="ALA",
              destination_country="Казахстан", is_domestic=0,
              flight_duration_min=225, distance_km=2500),
        Route(destination_city="Ташкент", destination_iata="TAS",
              destination_country="Узбекистан", is_domestic=0,
              flight_duration_min=270, distance_km=2850),
        Route(destination_city="Баку", destination_iata="GYD",
              destination_country="Азербайджан", is_domestic=0,
              flight_duration_min=175, distance_km=1790),
        Route(destination_city="Минск", destination_iata="MSQ",
              destination_country="Беларусь", is_domestic=0,
              flight_duration_min=100, distance_km=690),
        Route(destination_city="Бишкек", destination_iata="FRU",
              destination_country="Кыргызстан", is_domestic=0,
              flight_duration_min=270, distance_km=2920),
        Route(destination_city="Астана", destination_iata="NQZ",
              destination_country="Казахстан", is_domestic=0,
              flight_duration_min=210, distance_km=2200),
        Route(destination_city="Самарканд", destination_iata="SKD",
              destination_country="Узбекистан", is_domestic=0,
              flight_duration_min=285, distance_km=2980),
        Route(destination_city="Коломбо", destination_iata="CMB",
              destination_country="Шри-Ланка", is_domestic=0,
              flight_duration_min=570, distance_km=7200),
        Route(destination_city="Мале", destination_iata="MLE",
              destination_country="Мальдивы", is_domestic=0,
              flight_duration_min=540, distance_km=6500),
        Route(destination_city="Катманду", destination_iata="KTM",
              destination_country="Непал", is_domestic=0,
              flight_duration_min=420, distance_km=4900),
        Route(destination_city="Денпасар (Бали)", destination_iata="DPS",
              destination_country="Индонезия", is_domestic=0,
              flight_duration_min=660, distance_km=8900),
        Route(destination_city="Гоа", destination_iata="GOI",
              destination_country="Индия", is_domestic=0,
              flight_duration_min=360, distance_km=4100),
        Route(destination_city="Хургада", destination_iata="HRG",
              destination_country="Египет", is_domestic=0,
              flight_duration_min=270, distance_km=2870),
        Route(destination_city="Шарм-эш-Шейх", destination_iata="SSH",
              destination_country="Египет", is_domestic=0,
              flight_duration_min=285, distance_km=2950),
        Route(destination_city="Пхукет", destination_iata="HKT",
              destination_country="Таиланд", is_domestic=0,
              flight_duration_min=600, distance_km=7800),
        Route(destination_city="Куала-Лумпур", destination_iata="KUL",
              destination_country="Малайзия", is_domestic=0,
              flight_duration_min=630, distance_km=8200),
        Route(destination_city="Абу-Даби", destination_iata="AUH",
              destination_country="ОАЭ", is_domestic=0,
              flight_duration_min=255, distance_km=3450),
    ]
    db.add_all(routes)

    # ТЕСТОВЫЙ РЕЙС
    flight = Flight(
        flight_number="AL-1234",
        origin="Москва (SVO)",
        destination="Дубай (DXB)",
        departure_time="2026-04-15 10:30",
        arrival_time="2026-04-15 16:45",
        aircraft_type="Airbus A320",
        aircraft_reg="RA-89012",
        cruising_altitude=10500,
        cruising_speed=850,
        return_flight_number="AL-1235",
        return_departure_time="2026-04-15 18:30",
        return_arrival_time="2026-04-15 22:45"
    )
    db.add(flight)
    db.flush()

    # МЕНЮ
    menu_items = [
        MenuItem(flight_id=flight.id, name="Куриное филе с рисом",
                 description="Запечённое куриное филе с отварным рисом и овощами",
                 category="main", cabin_class="economy",
                 is_vegetarian=0, price=0.0),
        MenuItem(flight_id=flight.id, name="Паста с томатным соусом",
                 description="Паста пенне в томатном соусе с базиликом",
                 category="main", cabin_class="economy",
                 is_vegetarian=1, price=0.0),
        MenuItem(flight_id=flight.id, name="Шоколадный кекс",
                 description="Мягкий шоколадный кекс",
                 category="dessert", cabin_class="economy",
                 is_vegetarian=1, price=0.0),
        MenuItem(flight_id=flight.id, name="Кофе",
                 description="Американо или капучино",
                 category="drink", cabin_class="economy",
                 is_vegetarian=1, price=0.0),
        MenuItem(flight_id=flight.id, name="Стейк из говядины",
                 description="Стейк medium rare с картофельным пюре и спаржей",
                 category="main", cabin_class="business",
                 is_vegetarian=0, price=0.0),
    ]
    db.add_all(menu_items)

    # КОММЕРЧЕСКИЕ ПРЕДЛОЖЕНИЯ
    offers = [
        CommercialOffer(flight_id=flight.id, title="Duty Free",
                        description="Парфюмерия, косметика и алкоголь со скидкой до 30%",
                        category="duty_free"),
        CommercialOffer(flight_id=flight.id, title="AeroLine Бонус",
                        description="Накапливайте мили за каждый полёт и обменивайте на билеты",
                        category="loyalty"),
    ]
    db.add_all(offers)

    db.commit()
    db.close()
    print(f"База данных заполнена:")
    print(f"  - Самолётов: 30")
    print(f"  - Маршрутов: 45")
    print(f"  - Рейс: AL-1234 (Москва → Дубай)")

if __name__ == "__main__":
    seed()